// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using NUnit.Framework;

namespace PetClinicTestProject
{
    [TestFixture]
    public class AddVeterinarianTest : TestBase
    {

        [Test]
        public void addVeterinarian()
        {
            driver.FindElement(By.CssSelector(".vetsTab")).Click();
            driver.FindElement(By.CssSelector(".open li:nth-child(2) span:nth-child(2)")).Click();
            {
                var element = driver.FindElement(By.CssSelector("li:nth-child(4) > a"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            driver.FindElement(By.CssSelector(".ownerTab")).Click();
            AddVeterinarianPage.ClickNType(AddVeterinarianPage.firstName, "Ivan");
            AddVeterinarianPage.ClickNType(AddVeterinarianPage.lastName, "Ivanov");
            driver.FindElement(By.Id("specialties")).Click();
            {
                var dropdown = driver.FindElement(By.Id("specialties"));
                var selectElement = new SelectElement(dropdown);
                Thread.Sleep(3000);
                selectElement.SelectByText("Orthodontist");
            }
            AddVeterinarianPage.addVetherinarianButton.Click();
            var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".vetFullName")));
            Assert.That(driver.FindElement(By.CssSelector(".vetFullName")).Text, Is.EqualTo("Ivan Ivanov"));
        }
    }
}