// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using NUnit.Framework;
namespace PetClinicTestProject
{
    [TestFixture]
    public class DeleteSpecialityTest : TestBase
    {
        [Test]
        public void deleteSpeciality()
        {
            driver.FindElement(By.CssSelector("li:nth-child(5) > a")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".active"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            driver.FindElement(By.LinkText("Nurse .deleteSpecialty")).Click();
            Assert.IsFalse(driver.FindElement(By.LinkText("Nurse")).Displayed);
        }

    }
}