// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using NUnit.Framework;

namespace PetClinicTestProject
{
    [TestFixture]
    public class EditOwnerTest : TestBase
    {
        [Test]
        public void editOwner()
        {
            driver.FindElement(By.CssSelector(".ownerTab")).Click();
            driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }
            driver.FindElement(By.LinkText("Vasya Pupkin")).Click();
            driver.FindElement(By.CssSelector(".xd-container")).Click();
            driver.FindElement(By.CssSelector(".editOwner")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            EditOwnerPage.ClearNType(EditOwnerPage.firstName, "Vasya");
            driver.FindElement(By.Id("lastName")).Click();
            EditOwnerPage.ClearNType(EditOwnerPage.lastName, "Pupkin");
            driver.FindElement(By.Id("address")).Click();
            EditOwnerPage.ClearNType(EditOwnerPage.address, "Pushkina 11");
            driver.FindElement(By.Id("city")).Click();
            EditOwnerPage.ClearNType(EditOwnerPage.city, "Vyshhorod");
            driver.FindElement(By.Id("telephone")).Click();
            EditOwnerPage.ClearNType(EditOwnerPage.telephone, "0674664646");
            EditOwnerPage.updateOwnerButton.Click();
            var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".ownerPhone")));
            Assert.That(driver.FindElement(By.CssSelector(".ownerPhonee")).Text, Is.EqualTo("0674664646"));
        }
    }
}