// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using NUnit.Framework;
using NUnit.Allure.Core;
using Allure.Commons;
using NUnit.Allure.Steps;
using NUnit.Allure.Attributes;

namespace PetClinicTestProject
{
    [TestFixture]
    public class AddVeterinarianTest : Hooks
    {
        public AddVeterinarianTest() : base(BrowserType.Firefox) { }

        [Test]
        [AllureSuite("Check add veterinarian functionality")]
        public void addVeterinarian()
        {
            pages.Navigation.vetsTab.Click();
            pages.Navigation.vetsListLink.Click();
            {
                var element = driver.FindElement(By.CssSelector("li:nth-child(4) > a"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            Helpers.Scroll2Bottom(driver);
            pages.Navigation.ownerTab.Click();
            Helpers.ClickNType(pages.AddVeterinarian.firstName, "Ivan");
            Helpers.ClickNType(pages.AddVeterinarian.lastName, "Ivanov");
            driver.FindElement(By.Id("specialties")).Click();
            {
                var dropdown = driver.FindElement(By.Id("specialties"));
                var selectElement = new SelectElement(dropdown);
                Thread.Sleep(3000);
                selectElement.SelectByText("Orthodontist");
            }
            pages.AddVeterinarian.addVetherinarianButton.Click();
            var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".vetFullName")));
            Assert.That(driver.FindElement(By.CssSelector(".vetFullName")).Text, Is.EqualTo("Ivan Ivanov"));
        }
    }
}