// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using SeleniumExtras.WaitHelpers;
using NUnit.Framework;
using NUnit.Allure.Core;
using Allure.Commons;
using NUnit.Allure.Steps;
using NUnit.Allure.Attributes;

namespace PetClinicTestProject
{   
    [TestFixture]
    [Parallelizable]
    
    public class EditOwnerTest : Hooks
    {
        public EditOwnerTest() : base(BrowserType.Chrome) { }
        [Test]
        [TestCase("0967856070")]
        [TestCase("0996749327")]
        [AllureSuite("Check edit owner functionality")]
        public void editOwner(string telephone)
        {
            pages.Navigation.ownerTab.Click();
            pages.Navigation.ownerListLink.Click();
            {
                var element = driver.FindElement(By.CssSelector(".open li:nth-child(1) span:nth-child(2)"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            Helpers.Scroll2Bottom(driver);
            var owner = Owner.OwnerList.First().Name + "" + Owner.OwnerList.First().Surname;
            driver.FindElement(By.LinkText("Vasya Pupkin")).Click();
            driver.FindElement(By.CssSelector(".xd-container")).Click();
            driver.FindElement(By.CssSelector(".editOwner")).Click();
            driver.FindElement(By.Id("firstName")).Click();
            Helpers.ClearNType(pages.EditOwner.firstName, "Vasya");
            driver.FindElement(By.Id("lastName")).Click();
            Helpers.ClearNType(pages.EditOwner.lastName, "Pupkin");
            driver.FindElement(By.Id("address")).Click();
            Helpers.ClearNType(pages.EditOwner.address, "Pushkina 11");
            driver.FindElement(By.Id("city")).Click();
            Helpers.ClearNType(pages.EditOwner.city, "Vyshhorod");
            driver.FindElement(By.Id("telephone")).Click();
            Helpers.ClearNType(pages.EditOwner.telephone, telephone);
            pages.EditOwner.updateOwnerButton.Click();
            var wait = new WebDriverWait(driver, TimeSpan.FromSeconds(5));
            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector(".ownerPhone")));
            Assert.That(driver.FindElement(By.CssSelector(".ownerPhonee")).Text, Is.EqualTo("0674664646"));
        }
    }
}